Repository ahachulTeam/ahachul_web, pull requests merged in 2023-05, with the labels that each got.

#27 Feature/#21 필터 컴포넌트
  .eslintrc.json
  src/assets/icons/ic_arrow_down_min.svg
  src/assets/icons/index.ts
  src/assets/static/loastFound/filters.ts
  src/assets/static/loastFound/index.ts
  src/atoms/sample.ts
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/filter/Filter.tsx
  src/components/common/filter/index.ts
  src/components/common/filter/styled.ts
  src/components/common/index.ts
  src/components/domain/index.ts
  src/components/domain/lostFound/filterList/FilterList.tsx
  src/components/domain/lostFound/filterList/index.ts
  src/components/domain/lostFound/filterList/styled.ts
  src/components/domain/lostFound/index.ts
  src/hooks/index.ts
  src/hooks/useArrowKeyTrap.ts
  src/hooks/useDisclosure.ts
  src/hooks/useFilterList.ts
  src/hooks/useKeyTrap.ts
  src/hooks/useOnClickOutside.ts
  src/hooks/useSample.ts
  src/hooks/useScrollDirection.ts
  src/utils/navigation.ts
  yarn.lock
Labels: ✨ Feat, Notification

#34 Feat/32/커뮤니티 리스트 페이지 스크린
  package.json
  pages/_app.tsx
  pages/community/[id].tsx
  pages/community/index.tsx
  pages/onboarding/nickname/index.tsx
  pages/onboarding/redirect/index.tsx
  pnpm-lock.yaml
  public/dummy/images/dummy1.png
  public/dummy/images/dummy2.png
  public/dummy/images/dummy3.png
  src/assets/dummy/community.ts
  src/assets/static/tab.ts
  src/components/common/index.ts
  src/components/common/logo/LogoLink.tsx
  src/components/common/logo/styled.ts
  src/components/common/tab/Tab.tsx
  src/components/common/tab/hooks/useTab.ts
  src/components/common/tab/index.ts
  src/components/common/tab/styled.ts
  src/components/common/tagBtn/TagBtn.tsx
  src/components/common/tagBtn/index.ts
  src/components/common/tagBtn/styled.ts
  src/components/cta/forApp/ForApp.tsx
  src/components/domain/community/detail/container/CommunityDetailPageContainer.tsx
  src/components/domain/community/detail/container/styled.ts
  src/components/domain/community/index.ts
  src/components/domain/community/list/articleList/ArticleList.tsx
  src/components/domain/community/list/articleList/item/Item.tsx
  src/components/domain/community/list/articleList/item/styled.ts
  src/components/domain/community/list/articleList/styled.ts
  src/components/domain/community/list/container/CommunityPageContainer.tsx
  src/components/domain/community/list/container/styled.ts
  src/components/domain/community/list/hashtagList/HashtagList.tsx
  src/components/domain/community/list/hashtagList/styled.ts
  src/components/domain/community/list/index.ts
  src/components/domain/index.ts
  src/components/domain/onboarding/container/OnboardingPageContainer.tsx
  src/components/domain/onboarding/pages/redirect/container/RedirectPageContainer.tsx
  src/components/header/Header.tsx
  src/components/header/styled.ts
  src/constants/seo.ts
  src/queries/auth/useLoginMutation/index.ts
  src/styles/nprogress.css
  src/styles/themes/components/index.ts
  src/styles/themes/components/tag.ts
  src/styles/themes/foundations/size.ts
  src/styles/themes/theme.ts
  src/types/common.ts
  src/utils/time.ts
Labels: ✨ Feat

#36 fix: Mixed content 문제 해결
  pages/_document.tsx
Labels: 🔨 Fix

#37 ✨ Search Drawer 스크린 구현
  .eslintrc.json
  next.config.js
  package.json
  pages/_document.tsx
  pnpm-lock.yaml
  src/atoms/sample.ts
  src/components/common/drawer/search/SearchDrawer.tsx
  src/components/common/drawer/search/hooks/useSearchDrawer.ts
  src/components/common/drawer/search/styled.ts
  src/components/common/filter/Filter.tsx
  src/components/common/index.ts
  src/components/common/input/index.ts
  src/components/common/input/search/SearchInput.tsx
  src/components/common/input/search/styled.ts
  src/components/common/portal/AnimatePortal.tsx
  src/components/common/portal/Portal.tsx
  src/components/common/portal/index.ts
  src/components/common/tagBtn/TagBtn.tsx
  src/components/common/tagBtn/styled.ts
  src/components/domain/community/detail/container/CommunityDetailPageContainer.tsx
  src/components/domain/community/list/hashtagList/HashtagList.tsx
  src/components/domain/lostFound/filterList/FilterList.tsx
  src/components/header/Header.tsx
  src/constants/motions.ts
  src/hooks/useArrowKeyTrap.ts
  src/hooks/useDisclosure.ts
  src/hooks/useFilterList.ts
  src/hooks/useKeyTrap.ts
  src/hooks/useOnClickOutside.ts
  src/hooks/useScrollDirection.ts
  src/libs/providers/AppProvider.tsx
  src/styles/themes/components/input.ts
  src/styles/themes/components/tag.ts
  src/styles/themes/foundations/colors.ts
Labels: ✨ Feat

#41 유저 모니터링 위한 GA, HOTJAR, MIXPANEL 부착
  .babelrc
  .gitignore
  @types/environment.d.ts
  LICENSE
  next.config.js
  package.json
  pages/_document.tsx
  pnpm-lock.yaml
  src/components/index.ts
  src/components/layout/index.ts
  src/components/monitoring/MonitoringInitializer.tsx
  src/components/monitoring/index.ts
  src/libs/gtag.ts
  src/libs/providers/AppProvider.tsx
  src/utils/common.ts
  src/utils/event.ts
  tsconfig.json
Labels: ✨ Feat, ⚙️ Chore, Notification

#44 커뮤니티 디테일 페이지 스크린
  pages/_document.tsx
  pages/community/[id].tsx
  src/components/domain/community/detail/comments/Comments.tsx
  src/components/domain/community/detail/comments/styled.ts
  src/components/domain/community/detail/container/CommunityDetailPageContainer.tsx
  src/components/domain/community/detail/container/styled.ts
  src/components/domain/community/detail/contents/Contents.tsx
  src/components/domain/community/detail/contents/styled.ts
  src/components/domain/community/detail/index.ts
  src/components/domain/community/index.ts
  src/styles/global.ts
  src/styles/themes/components/button.ts
  src/styles/themes/components/input.ts
  src/styles/themes/foundations/colors.ts
  src/styles/themes/foundations/fonts.ts
  src/types/community.ts
Labels: ✨ Feat

#45 유실물 목록 페이지 스크린
  pages/lost/[id].tsx
  pages/lost/index.tsx
  public/images/default_thumbnail.svg
  src/assets/icons/ic_comment.svg
  src/assets/icons/ic_love.svg
  src/assets/icons/ic_menu.svg
  src/assets/icons/ic_quilt.svg
  src/assets/icons/index.ts
  src/assets/static/navbar.ts
  src/atoms/view.ts
  src/components/common/badge/Badge.tsx
  src/components/common/carousel/Carousel.tsx
  src/components/common/carousel/index.ts
  src/components/common/carousel/styled.ts
  src/components/common/filter/Filter.tsx
  src/components/common/filter/styled.ts
  src/components/common/index.ts
  src/components/common/toggle/Toggle.tsx
  src/components/domain/index.ts
  src/components/domain/lost/detail/container/LostDetailContainer.tsx
  src/components/domain/lost/detail/container/index.ts
  src/components/domain/lost/detail/container/styled.ts
  src/components/domain/lost/detail/index.ts
  src/components/domain/lost/index.ts
  src/components/domain/lost/list/container/LostContainer.tsx
  src/components/domain/lost/list/container/index.ts
  src/components/domain/lost/list/container/styled.ts
  src/components/domain/lost/list/controller/Controller.tsx
  src/components/domain/lost/list/controller/changeView/ChangeView.tsx
  src/components/domain/lost/list/controller/changeView/styled.ts
  src/components/domain/lost/list/controller/filterList/FilterList.tsx
  src/components/domain/lost/list/controller/filterList/styled.ts
  src/components/domain/lost/list/controller/styled.ts
  src/components/domain/lost/list/index.ts
  src/components/domain/lost/list/lostList/LostList.tsx
  src/components/domain/lost/list/lostList/item/LostItem.tsx
  src/components/domain/lost/list/lostList/item/styled.ts
  src/components/domain/lost/list/lostList/styled.ts
  src/components/domain/lostFound/filterList/index.ts
  src/components/domain/lostFound/index.ts
  src/components/domain/onboarding/carousel/Carousel.tsx
  src/components/domain/onboarding/carousel/OnboardingCarousel.tsx
  src/components/domain/onboarding/carousel/index.ts
  src/components/domain/onboarding/carousel/styled.ts
  src/components/domain/onboarding/container/OnboardingPageContainer.tsx
  src/components/index.ts
  src/components/layout/Layout.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/index.ts
  src/components/layout/header/styled.ts
  src/components/layout/navbar/Navbar.styled.ts
  src/components/layout/navbar/Navbar.tsx
  src/components/layout/navbar/index.ts
  src/components/layout/navbar/item/NavItem.styled.ts
  src/components/layout/navbar/item/NavItem.tsx
  src/constants/path.ts
  src/styles/global.ts
  src/styles/themes/components/badge.ts
  src/styles/themes/foundations/colors.ts
  src/styles/themes/foundations/fonts.ts
Labels: ✨ Feat

#59 [CHORE] swiper.js 라이브러리 충돌 이슈
  .eslintrc.js
  .github/workflows/ci-ahhachul-app.yml
  .pnp.cjs
  .yarn/cache/@emotion-eslint-plugin-npm-11.11.0-27e29c96e4-2d555b6790.zip
  .yarn/cache/ssr-window-npm-4.0.2-01f9c0151e-df18260092.zip
  .yarn/cache/swiper-npm-9.3.2-a973b47a13-9ccb6a0ef6.zip
  apps/web/package.json
  apps/web/src/components/common/carousel/Carousel.tsx
  apps/web/src/components/common/carousel/index.ts
  apps/web/src/components/common/carousel/styled.ts
  apps/web/src/components/common/index.ts
  apps/web/src/components/domain/onboarding/carousel/OnboardingCarousel.tsx
  apps/web/src/components/domain/onboarding/carousel/index.ts
  apps/web/src/components/domain/onboarding/carousel/styled.ts
  apps/web/src/components/domain/onboarding/container/OnboardingPageContainer.tsx
  package.json
  yarn.lock
Labels: ⚙️ Chore

#65 'next/font' 사용해서 폰트 적용하기
  apps/web/pages/_document.tsx
  apps/web/public/fonts/Pretendard-Bold.otf
  apps/web/public/fonts/Pretendard-Medium.otf
  apps/web/public/fonts/Pretendard-Regular.otf
  apps/web/public/fonts/Pretendard-SemiBold.otf
  apps/web/src/assets/fonts/Pretendard.woff2
  apps/web/src/assets/fonts/pretendard.ts
  apps/web/src/components/common/bottomSheet/BottomSheet.tsx
  apps/web/src/components/common/drawer/search/SearchDrawer.tsx
  apps/web/src/libs/providers/AppProvider.tsx
  apps/web/src/styles/global.ts
  apps/web/src/styles/themes/foundations/fonts.ts
Labels: ✨ Feat

#67 Portal 컴포넌트 사용 방식 소소한 수정
  apps/web/pages/_document.tsx
  apps/web/src/components/common/bottomSheet/BottomSheet.tsx
  apps/web/src/components/common/drawer/search/SearchDrawer.tsx
  apps/web/src/components/common/drawer/search/styled.ts
  apps/web/src/components/common/portal/AnimatePortal.tsx
  apps/web/src/components/common/portal/MotionPortal.tsx
  apps/web/src/components/common/portal/Portal.tsx
  apps/web/src/components/common/portal/index.ts
Labels: ✨ Feat, 🪛 Refactor

#75 [FEATURE] package/ui story 작성
  packages/ui/.storybook/assets/Pretendard.woff2
  packages/ui/.storybook/preview-head.html
  packages/ui/src/stories/colors/ColorGroup.tsx
  packages/ui/src/stories/colors/Colors.stories.tsx
  packages/ui/src/stories/colors/styled.ts
  packages/ui/src/stories/typography/Typography.stories.mdx
Labels: ✨ Feat

#76 유저 닉네임 설정하기
  apps/web/pages/_app.tsx
  apps/web/pages/index.tsx
  apps/web/pages/my-page.tsx
  apps/web/pages/onboarding/index.tsx
  apps/web/pages/onboarding/nickname/index.tsx
  apps/web/pages/onboarding/redirect/index.tsx
  apps/web/src/components/common/index.ts
  apps/web/src/components/common/stagger/Stagger.tsx
  apps/web/src/components/common/stagger/index.ts
  apps/web/src/components/domain/onboarding/container/OnboardingPageContainer.tsx
  apps/web/src/components/domain/onboarding/pages/nickname/containter/NicknamePageContainer.tsx
  apps/web/src/components/domain/onboarding/pages/nickname/containter/styled.ts
  apps/web/src/components/domain/onboarding/pages/redirect/container/RedirectPageContainer.tsx
  apps/web/src/constants/motions.ts
  packages/ds/src/tokens/fonts.ts
  packages/ui/src/components/fullHeight/FullHeight.tsx
  packages/ui/src/components/fullHeight/index.ts
  packages/ui/src/components/index.ts
  packages/ui/tsconfig.tsbuildinfo
Labels: ✨ Feat

#77 Dynamic Header 제작하기
  apps/web/pages/404.tsx
  apps/web/pages/alarm.tsx
  apps/web/pages/community/[id].tsx
  apps/web/pages/community/index.tsx
  apps/web/pages/index.tsx
  apps/web/pages/lost/[id].tsx
  apps/web/pages/lost/index.tsx
  apps/web/pages/my-page.tsx
  apps/web/pages/onboarding/nickname/index.tsx
  apps/web/src/components/common/drawer/index.ts
  apps/web/src/components/common/drawer/search/SearchDrawer.tsx
  apps/web/src/components/common/drawer/search/index.ts
  apps/web/src/components/common/index.ts
  apps/web/src/components/domain/community/detail/container/CommunityDetailPageContainer.tsx
  apps/web/src/components/domain/community/detail/container/index.ts
  apps/web/src/components/domain/community/detail/header/CommunityDetailHeader.tsx
  apps/web/src/components/domain/community/detail/header/index.ts
  apps/web/src/components/domain/community/detail/index.ts
  apps/web/src/components/domain/community/list/container/CommunityPageContainer.tsx
  apps/web/src/components/domain/community/list/container/index.ts
  apps/web/src/components/domain/community/list/header/CommunityHeader.tsx
  apps/web/src/components/domain/community/list/header/index.ts
  apps/web/src/components/domain/community/list/index.ts
  apps/web/src/components/domain/home/header/HomeHeader.tsx
  apps/web/src/components/domain/home/header/index.ts
  apps/web/src/components/domain/home/index.ts
  apps/web/src/components/domain/lost/detail/header/LostDetailHeader.tsx
  apps/web/src/components/domain/lost/detail/header/index.ts
  apps/web/src/components/domain/lost/detail/index.ts
  apps/web/src/components/domain/lost/list/header/LostHeader.tsx
  apps/web/src/components/domain/lost/list/header/index.ts
  apps/web/src/components/domain/lost/list/index.ts
  apps/web/src/components/domain/onboarding/pages/nickname/container/NicknamePageContainer.tsx
  apps/web/src/components/domain/onboarding/pages/nickname/container/index.ts
  apps/web/src/components/domain/onboarding/pages/nickname/container/styled.ts
  apps/web/src/components/domain/onboarding/pages/nickname/containter/index.ts
  apps/web/src/components/domain/onboarding/pages/nickname/header/NicknameHeader.tsx
  apps/web/src/components/domain/onboarding/pages/nickname/header/index.ts
  apps/web/src/components/domain/onboarding/pages/nickname/index.ts
  apps/web/src/components/layout/Layout.tsx
  apps/web/src/components/layout/header/Header.tsx
  apps/web/src/components/layout/header/index.ts
  apps/web/src/components/layout/header/styled.ts
  apps/web/src/components/layout/index.ts
  apps/web/src/constants/header.tsx
  apps/web/src/constants/index.ts
  packages/lib/src/types/index.ts
  packages/lib/src/types/void.ts
Labels: ✨ Feat

#79 커뮤니티 페이지 글 등록 API 연동하기
  .pnp.cjs
  .yarn/cache/react-hook-form-npm-7.43.9-3a3f4f3335-65b94de625.zip
  apps/web/package.json
  apps/web/pages/community/generate.tsx
  apps/web/pages/community/index.tsx
  apps/web/src/apis/community.ts
  apps/web/src/apis/index.ts
  apps/web/src/components/common/bottomSheet/BottomSheet.tsx
  apps/web/src/components/domain/community/generate/container/CommunityGenerateContainer.tsx
  apps/web/src/components/domain/community/generate/container/styled.ts
  apps/web/src/components/domain/community/generate/controller/SubwayLineFilter.tsx
  apps/web/src/components/domain/community/generate/controller/index.ts
  apps/web/src/components/domain/community/generate/controller/styled.ts
  apps/web/src/components/domain/community/generate/hooks/useArticleForm.ts
  apps/web/src/components/domain/community/generate/hooks/useSubwayLine.ts
  apps/web/src/components/domain/community/generate/index.ts
  apps/web/src/components/domain/community/index.ts
  apps/web/src/components/domain/community/list/articleList/item/Item.tsx
  apps/web/src/components/domain/community/list/articleList/item/styled.ts
  apps/web/src/components/domain/community/list/articleList/styled.ts
  apps/web/src/components/domain/community/list/container/CommunityPageContainer.tsx
  apps/web/src/components/domain/community/list/container/styled.ts
  apps/web/src/constants/subway.ts
  apps/web/src/queries/community/useCreateArticle.ts
  apps/web/src/types/community.ts
  packages/ds/src/tokens/colors.ts
  packages/ui/src/components/button/styled.ts
  packages/ui/src/components/tab/Tab.tsx
  yarn.lock
Labels: ✨ Feat

#84 민원접수 페이지 스크린 구현
  apps/web/pages/community/index.tsx
  apps/web/pages/complaint/[id].tsx
  apps/web/pages/complaint/index.tsx
  apps/web/public/illust/onboding/_3.svg
  apps/web/src/components/common/filter/Filter.tsx
  apps/web/src/components/common/floatingButton/FloatingBtn.tsx
  apps/web/src/components/common/floatingButton/index.ts
  apps/web/src/components/common/floatingButton/styled.ts
  apps/web/src/components/common/index.ts
  apps/web/src/components/cta/forApp/ForApp.tsx
  apps/web/src/components/domain/alarm/header/AlarmHeader.tsx
  apps/web/src/components/domain/community/generate/controller/SubwayLineFilter.tsx
  apps/web/src/components/domain/community/list/header/CommunityHeader.tsx
  apps/web/src/components/domain/complaint/callCenterDrawer/CallCenterDrawer.tsx
  apps/web/src/components/domain/complaint/callCenterDrawer/index.ts
  apps/web/src/components/domain/complaint/callCenterDrawer/styled.ts
  apps/web/src/components/domain/complaint/detail/container/ComplaintDetailPageContainer.tsx
  apps/web/src/components/domain/complaint/detail/container/index.ts
  apps/web/src/components/domain/complaint/detail/header/ComplaintDetailHeader.tsx
  apps/web/src/components/domain/complaint/detail/header/index.ts
  apps/web/src/components/domain/complaint/detail/index.ts
  apps/web/src/components/domain/complaint/index.ts
  apps/web/src/components/domain/complaint/list/card/Card.tsx
  apps/web/src/components/domain/complaint/list/card/styled.ts
  apps/web/src/components/domain/complaint/list/cardIcon/CardIcon.tsx
  apps/web/src/components/domain/complaint/list/cardIcon/styled.ts
  apps/web/src/components/domain/complaint/list/container/ComplaintPageContainer.tsx
  apps/web/src/components/domain/complaint/list/container/index.ts
  apps/web/src/components/domain/complaint/list/container/styled.ts
  apps/web/src/components/domain/complaint/list/emergency/Emergency.tsx
  apps/web/src/components/domain/complaint/list/emergency/cards/Patient.tsx
  apps/web/src/components/domain/complaint/list/emergency/cards/Sexual.tsx
  apps/web/src/components/domain/complaint/list/emergency/cards/Violence.tsx
  apps/web/src/components/domain/complaint/list/emergency/styled.ts
  apps/web/src/components/domain/complaint/list/environment/Environment.tsx
  apps/web/src/components/domain/complaint/list/environment/cards/Announcement.tsx
  apps/web/src/components/domain/complaint/list/environment/cards/Facilities.tsx
  apps/web/src/components/domain/complaint/list/environment/cards/Impediment.tsx
  apps/web/src/components/domain/complaint/list/environment/cards/Temperature.tsx
  apps/web/src/components/domain/complaint/list/environment/cards/index.ts
  apps/web/src/components/domain/complaint/list/environment/styled.ts
  apps/web/src/components/domain/complaint/list/header/ComplaintHeader.tsx
  apps/web/src/components/domain/complaint/list/header/index.ts
  apps/web/src/components/domain/complaint/list/index.ts
  apps/web/src/components/domain/home/header/HomeHeader.tsx
  apps/web/src/components/domain/lost/detail/header/LostDetailHeader.tsx
  apps/web/src/components/domain/lost/list/header/LostHeader.tsx
  apps/web/src/components/domain/main/container/MainPageContainer.tsx
  apps/web/src/components/domain/onboarding/container/OnboardingPageContainer.tsx
  apps/web/src/components/layout/header/Header.tsx
  apps/web/src/constants/path.ts
  apps/web/src/constants/subway.ts
  apps/web/src/hooks/useTab.ts
  apps/web/src/types/variants.ts
  packages/ds/src/tokens/colors.ts
  packages/ds/src/tokens/fonts.ts
  packages/lib/src/hooks/useDisclosure.ts
  packages/lib/tsconfig.tsbuildinfo
  packages/ui/tsconfig.tsbuildinfo
Labels: ✨ Feat
