Repository ahachulTeam/ahachul_web, pull requests merged in 2023-09, with the labels that each got.

#139 [FEATURE] StickyArea, NavBar 싱크 안맞는 이슈 수정
  apps/web/src/components/domain/community/generate/container/CommunityGenerateContainer.tsx
  apps/web/src/components/domain/lost/generate/container/LostGenerateContainer.tsx
  apps/web/src/components/layout/navbar/Navbar.tsx
  apps/web/src/hooks/index.ts
  apps/web/src/hooks/useNavigationBar.ts
  packages/lib/src/hooks/useScrollDirection.ts
Labels: ✨ Feat

#137 [FEATURE] 습득물 작성 페이지 디자인 수정
  apps/web/src/components/domain/lost/generate/container/LostGenerateContainer.tsx
  apps/web/src/components/domain/lost/generate/container/styled.ts
  apps/web/src/components/domain/lost/generate/controller/SubwayLineFilter.tsx
  apps/web/src/components/domain/lost/generate/controller/styled.ts
  apps/web/src/components/domain/lost/generate/hooks/useSubwayLine.ts
  node_modules/.cache/storybook/dev-server/a5a8bf6e622aef57065c6498611f40c911543d7d-3920d97c51b8ad2521918fb1205babd22b0ed3d7
  node_modules/.cache/storybook/dev-server/a5a8bf6e622aef57065c6498611f40c911543d7d-43fdebe5fc35e4e9fabee9a83c7faea931b05ea0
  node_modules/.cache/storybook/dev-server/a5a8bf6e622aef57065c6498611f40c911543d7d-f086b87885981c04ce7a583ff90a49313de83de7
  packages/ds/src/tokens/colors.ts
  packages/ui/src/components/input/Input.tsx
  packages/ui/src/components/textarea/Textarea.tsx
Labels: 🌈 Style

#140 해쉬태그 인기 순위 인풋 제작 및 api 연동
  apps/web/pages/_app.tsx
  apps/web/pages/_document.tsx
  apps/web/pages/index.tsx
  apps/web/public/illust/train.svg
  apps/web/src/apis/auth.ts
  apps/web/src/apis/common.ts
  apps/web/src/apis/gloabal.ts
  apps/web/src/apis/index.ts
  apps/web/src/apis/users.ts
  apps/web/src/assets/icons/ic_info_fill.svg
  apps/web/src/assets/icons/index.ts
  apps/web/src/components/common/drawer/search/styled.ts
  apps/web/src/components/domain/community/list/articleList/item/CommunityItem.skeleton.tsx
  apps/web/src/components/domain/community/list/header/CommunityHeader.tsx
  apps/web/src/components/domain/home/community/Community.tsx
  apps/web/src/components/domain/home/community/item/Item.tsx
  apps/web/src/components/domain/home/community/item/styled.ts
  apps/web/src/components/domain/home/community/styled.ts
  apps/web/src/components/domain/home/container/MainPageContainer.tsx
  apps/web/src/components/domain/home/container/styled.ts
  apps/web/src/components/domain/home/index.ts
  apps/web/src/components/domain/home/subway/SubwayInformation.tsx
  apps/web/src/components/domain/home/subwayOverview/SubwayOverview.tsx
  apps/web/src/components/domain/home/subwayOverview/styled.ts
  apps/web/src/components/domain/index.ts
  apps/web/src/components/domain/lost/list/lostFoundList/list/item/LostItem.skeleton.tsx
  apps/web/src/components/domain/main/index.ts
  apps/web/src/components/layout/header/Header.tsx
  apps/web/src/components/layout/header/styled.ts
  apps/web/src/components/public/AppInner.tsx
  apps/web/src/components/public/Train.tsx
  apps/web/src/components/public/TrainEachBox.tsx
  apps/web/src/components/public/TrainSvg.tsx
  apps/web/src/constants/pathValues.ts
  apps/web/src/context/AuthProvider.tsx
  apps/web/src/libs/providers/AppProvider.tsx
  apps/web/src/libs/providers/NProgress.tsx
  apps/web/src/libs/providers/ReactQuery.tsx
  apps/web/src/queries/auth/useLoginMutation/index.ts
  apps/web/src/queries/global/hot-hashtags.ts
  apps/web/src/queries/user/useMyProfileMutation/index.ts
  apps/web/src/queries/user/useMyProfileQuery/index.ts
  apps/web/src/queries/user/useUserProfileQuery/index.ts
  apps/web/src/queries/user/useVerifyNickname/index.ts
  apps/web/src/types/auth.ts
  apps/web/src/types/global.ts
  apps/web/src/utils/pathValues.ts
  apps/web/src/utils/tokenService.ts
  packages/ds/src/theme.ts
  packages/ds/src/tokens/common.ts
  packages/ds/src/tokens/index.ts
  packages/lib/tsconfig.tsbuildinfo
  packages/ui/src/components/search/styled.ts
  packages/ui/tsconfig.tsbuildinfo
Labels: ✨ Feat, 👀 Draft

#120 [FEATURE] 유실물 상세 페이지
  apps/web/pages/_app.tsx
  apps/web/pages/complaint/[id].tsx
  apps/web/pages/lost/[id].tsx
  apps/web/pages/lost/index.tsx
  apps/web/src/apis/complaint.ts
  apps/web/src/apis/lost.ts
  apps/web/src/apis/train.ts
  apps/web/src/assets/icons/ic_arrow.svg
  apps/web/src/assets/icons/ic_pin.svg
  apps/web/src/assets/icons/index.ts
  apps/web/src/components/common/carousel/Carousel.tsx
  apps/web/src/components/common/carousel/styled.ts
  apps/web/src/components/common/floatingButton/styled.ts
  apps/web/src/components/domain/complaint/generate/container/ComplainGenerateContainer.styled.ts
  apps/web/src/components/domain/complaint/generate/contents/Facilities.tsx
  apps/web/src/components/domain/complaint/generate/contents/Impediment.tsx
  apps/web/src/components/domain/complaint/generate/contents/Patient.tsx
  apps/web/src/components/domain/complaint/generate/contents/Sexual.tsx
  apps/web/src/components/domain/complaint/generate/contents/Temperature.tsx
  apps/web/src/components/domain/complaint/generate/contents/Violence.tsx
  apps/web/src/components/domain/complaint/generate/header/ComplaintGenerateHeader.tsx
  apps/web/src/components/domain/complaint/list/token/emergency/Emergency.tsx
  apps/web/src/components/domain/complaint/list/token/environment/Environment.tsx
  apps/web/src/components/domain/lost/detail/container/LostDetailContainer.styled.ts
  apps/web/src/components/domain/lost/detail/container/LostDetailContainer.tsx
  apps/web/src/components/domain/lost/detail/contents/LostDetailContents.styled.ts
  apps/web/src/components/domain/lost/detail/contents/LostDetailContents.tsx
  apps/web/src/components/domain/lost/detail/contents/carousel/LostCarousel.styled.ts
  apps/web/src/components/domain/lost/detail/contents/carousel/LostCarousel.tsx
  apps/web/src/components/domain/lost/detail/contents/contentHeader/ContentHeader.styled.ts
  apps/web/src/components/domain/lost/detail/contents/contentHeader/ContentHeader.tsx
  apps/web/src/components/domain/lost/detail/contents/contentInfo/ContentInfo.styled.ts
  apps/web/src/components/domain/lost/detail/contents/contentInfo/ContentInfo.tsx
  apps/web/src/components/domain/lost/detail/contents/contentInfo/contentDetail/ContentDetail.styled.ts
  apps/web/src/components/domain/lost/detail/contents/contentInfo/contentDetail/ContentDetail.tsx
  apps/web/src/components/domain/lost/detail/contents/index.ts
  apps/web/src/components/domain/lost/detail/otherLostFounds/OtherLostFounds.styled.ts
  apps/web/src/components/domain/lost/detail/otherLostFounds/OtherLostFounds.tsx
  apps/web/src/components/domain/lost/detail/otherLostFounds/index.ts
  apps/web/src/components/domain/lost/detail/otherLostFounds/item/OtherLostFoundItem.styled.ts
  apps/web/src/components/domain/lost/detail/otherLostFounds/item/OtherLostFoundItem.tsx
  apps/web/src/components/domain/lost/detail/stickyArea/StickyArea.styled.ts
  apps/web/src/components/domain/lost/detail/stickyArea/StickyArea.tsx
  apps/web/src/components/domain/lost/detail/stickyArea/index.ts
  apps/web/src/components/domain/onboarding/carousel/OnboardingCarousel.tsx
  apps/web/src/components/domain/onboarding/carousel/styled.ts
  apps/web/src/hooks/index.ts
  apps/web/src/hooks/useNavigationBar.ts
  apps/web/src/hooks/useOwnArticle.ts
  apps/web/src/libs/index.ts
  apps/web/src/queries/complaint/usePostComplaintMessage.ts
  apps/web/src/queries/lost/index.ts
  apps/web/src/queries/lost/useFetchLostDetail.ts
  packages/ds/src/tokens/colors.ts
  packages/ds/src/tokens/fonts.ts
  packages/lib/src/types/line.ts
  packages/lib/tsconfig.tsbuildinfo
  packages/ui/src/components/badge/styled.ts
  packages/ui/tsconfig.tsbuildinfo
Labels: ✨ Feat, 👀 Draft
