Repository ahachulTeam/ahachul_web, pull requests merged in 2023-07, with the labels that each got.

#107 [REFACTORING] UI 공용 컴포넌트 수정
  apps/web/src/components/domain/main/community/item/Item.tsx
  packages/lib/src/hooks/useBoolean.ts
  packages/lib/src/types/line.ts
  packages/ui/src/components/badge/Badge.stories.tsx
  packages/ui/src/components/badge/Badge.tsx
  packages/ui/src/components/badge/styled.ts
  packages/ui/src/components/checkbox/Checkbox.stories.tsx
  packages/ui/src/components/checkbox/Checkbox.tsx
  packages/ui/src/components/checkbox/styled.ts
Labels: 🪛 Refactor

#94 [FEATURE] 유실물 조회 API 연동
  .eslintrc.js
  .pnp.cjs
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.29.12-ecc788c3e7-095c1f0fb8.zip
  .yarn/cache/copy-anything-npm-3.0.5-562d15fb3f-d39f6601c1.zip
  .yarn/cache/is-what-npm-4.1.15-328677a458-fe27f6cd4a.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.12.3-5863896cb5-3549cc1d03.zip
  apps/web/@types/next.d.ts
  apps/web/package.json
  apps/web/pages/_app.tsx
  apps/web/pages/lost/index.tsx
  apps/web/src/apis/axios.ts
  apps/web/src/apis/lost.ts
  apps/web/src/assets/static/loastFound/filters.ts
  apps/web/src/components/common/index.ts
  apps/web/src/components/common/intersectionArea/IntersectionArea.styled.ts
  apps/web/src/components/common/intersectionArea/IntersectionArea.tsx
  apps/web/src/components/common/intersectionArea/index.ts
  apps/web/src/components/domain/lost/list/container/LostContainer.tsx
  apps/web/src/components/domain/lost/list/container/styled.ts
  apps/web/src/components/domain/lost/list/controller/filterList/FilterList.tsx
  apps/web/src/components/domain/lost/list/lostList/LostList.tsx
  apps/web/src/components/domain/lost/list/lostList/item/LostItem.skeleton.tsx
  apps/web/src/components/domain/lost/list/lostList/item/LostItem.tsx
  apps/web/src/components/domain/lost/list/lostList/item/index.ts
  apps/web/src/components/domain/lost/list/lostList/item/styled.ts
  apps/web/src/components/domain/lost/list/lostList/styled.ts
  apps/web/src/components/layout/styled.ts
  apps/web/src/constants/error.ts
  apps/web/src/hooks/useFilterList.ts
  apps/web/src/hooks/useTab.ts
  apps/web/src/libs/providers/AppProvider.tsx
  apps/web/src/libs/providers/ReactQuery.tsx
  apps/web/src/queries/lost/index.ts
  apps/web/src/queries/lost/keys.ts
  apps/web/src/queries/lost/useFetchLostPosts.ts
  apps/web/src/types/common.ts
  apps/web/src/types/lost.ts
  apps/web/src/utils/option.ts
  apps/web/src/utils/tokenService.ts
  apps/web/src/utils/try.ts
  yarn.lock
Labels: ✨ Feat, 🪛 Refactor

#109 [FEATURE] SEO 컴포넌트 추가
  apps/web/src/constants/seo.ts
  apps/web/src/libs/SEO.tsx
  apps/web/src/utils/seo.ts
Labels: ✨ Feat

#119 [FEATURE] 공용 버튼 컴포넌트 variant 추가
  packages/ui/src/components/button/Button.stories.ts
  packages/ui/src/components/button/Button.tsx
  packages/ui/src/components/button/styled.ts
Labels: ✨ Feat

#117 [FEATURE] 유실물 목록 페이지 이미지 연결 & 스켈레톤 개선
  apps/web/next.config.js
  apps/web/src/components/domain/lost/list/container/LostContainer.tsx
  apps/web/src/components/domain/lost/list/lostFoundList/acquire/AcquireList.tsx
  apps/web/src/components/domain/lost/list/lostFoundList/index.ts
  apps/web/src/components/domain/lost/list/lostFoundList/list/LostFoundList.skeleton.tsx
  apps/web/src/components/domain/lost/list/lostFoundList/list/LostFoundList.tsx
  apps/web/src/components/domain/lost/list/lostFoundList/list/item/LostItem.skeleton.tsx
  apps/web/src/components/domain/lost/list/lostFoundList/list/item/LostItem.tsx
  apps/web/src/components/domain/lost/list/lostFoundList/list/item/index.ts
  apps/web/src/components/domain/lost/list/lostFoundList/list/item/styled.ts
  apps/web/src/components/domain/lost/list/lostFoundList/list/styled.ts
  apps/web/src/components/domain/lost/list/lostFoundList/lost/LostList.tsx
  apps/web/src/hooks/useTab.ts
  apps/web/src/queries/lost/useFetchLostPosts.ts
  apps/web/src/types/lost.ts
Labels: ✨ Feat, 🪛 Refactor

#114 [FEATURE] RadioButton 컴포넌트 구현
  .eslintrc.js
  packages/ui/src/components/index.ts
  packages/ui/src/components/radioButton/RadioButton.constants.ts
  packages/ui/src/components/radioButton/RadioButton.styled.ts
  packages/ui/src/components/radioButton/RadioButton.tsx
  packages/ui/src/components/radioButton/RadioButton.types.ts
  packages/ui/src/components/radioButton/index.ts
  packages/ui/src/components/switchCase/SwitchCase.tsx
  packages/ui/src/components/switchCase/SwitchCase.types.ts
  packages/ui/src/components/switchCase/index.ts
Labels: ✨ Feat

#128 [FIX] 버셀 프리뷰 배포 오류
  .pnp.cjs
  .yarn/cache/@types-react-dom-npm-18.0.11-27f8db2995-579691e4d5.zip
  .yarn/cache/@types-react-npm-18.0.28-c6157151cc-e752df9611.zip
  apps/web/package.json
  packages/ui/package.json
  yarn.lock
Labels: 🔨 Fix
