Repository ahachulTeam/ahachul_web, pull requests merged in 2024-12, with the labels that each got.

#273 chore: 피그마 디자인 시스템 테일윈드 테마로 적용
  services/one-app/src/common/constants/colors.ts
  services/one-app/tailwind.config.ts
Labels: ⚙️ Chore

#274 feat: 유실물 페이지 (웹) UI 스타일링
  services/one-app/next.config.mjs
  services/one-app/package.json
  services/one-app/src/app/(site)/layout.tsx
  services/one-app/src/app/(site)/lost-found/[lostId]/page.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/LostTypeBadge.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/PostDetail.tsx
  services/one-app/src/app/(site)/lost-found/_components/searchResults/filterList/FilterList.tsx
  services/one-app/src/app/(site)/lost-found/_components/searchResults/searchedList/SearchedList.tsx
  services/one-app/src/app/(site)/lost-found/_lib/useLostFoundFilterStore.ts
  services/one-app/src/app/(site)/lost-found/page.tsx
  services/one-app/src/common/assets/icons/comment.tsx
  services/one-app/src/common/assets/icons/search.tsx
  services/one-app/src/common/assets/icons/subway-logo/index.ts
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_1.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_2.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_3.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_4.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_5.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_6.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_7.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_8.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_9.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_GTX_A.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_경강.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_경의중앙.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_경춘.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_공항.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_김포골드.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_서해.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_수인분당.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_신림.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_신분당.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_에버라인.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_우이신설.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_의정부.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_인천_1.svg
  services/one-app/src/common/assets/icons/subway-logo/subway_logo_인천_2.svg
  services/one-app/src/common/assets/icons/svgs/bookmark.svg
  services/one-app/src/common/assets/icons/svgs/dot.svg
  services/one-app/src/common/assets/icons/svgs/ellipsis.svg
  services/one-app/src/common/components/Article/ArticleCard.tsx
  services/one-app/src/common/components/Article/ArticleImages.tsx
  services/one-app/src/common/components/Article/FullImageDialog.tsx
  services/one-app/src/common/components/Article/FullImageViewer.tsx
  services/one-app/src/common/components/Filter/DropdownFilter.tsx
  services/one-app/src/common/components/Filter/ResetFilter.tsx
  services/one-app/src/common/components/Filter/SearchFilter.tsx
  services/one-app/src/common/components/Filters/ResetFilter.tsx
  services/one-app/src/common/components/Subway/subway-logo-icon-map.tsx
  services/one-app/src/common/utils/subway.ts
  services/one-app/src/globals.d.ts
  services/one-app/src/model/LostFound.ts
  services/one-app/src/model/Post.ts
  services/one-app/src/store/filter.ts
  services/one-app/tsconfig.json
  yarn.lock
Labels: 🌈 Style

#278 chore: 이슈 번호 자동으로 붙도록 설정 추가
  .husky/pre-commit
  .husky/prepare-commit-msg
Labels: ⚙️ Chore

#276 feat: 유실물 리스트, 상세, 댓글 목록, 댓글 입력 컴포넌트 UI 상세 작업
  services/one-app/package.json
  services/one-app/public/images/lost112.png
  services/one-app/src/app/(site)/_component/Editor/LexicalSyntaxContentParser.tsx
  services/one-app/src/app/(site)/_component/Editor/index.tsx
  services/one-app/src/app/(site)/_component/Editor/plugins/OnChangePlugin.tsx
  services/one-app/src/app/(site)/_component/Editor/plugins/SpeechToTextPlugin.tsx
  services/one-app/src/app/(site)/_component/Editor/plugins/SpeechToTextToolbarPlugin.tsx
  services/one-app/src/app/(site)/_hook/useReport.ts
  services/one-app/src/app/(site)/lost-found/[lostId]/page.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/CommentList.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/CommentTextField.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/Lost112ArticleTable.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/PostDetail.tsx
  services/one-app/src/app/(site)/lost-found/_components/postDetail/RecommendArticles.tsx
  services/one-app/src/app/(site)/lost-found/_components/searchResults/searchedList/SearchedList.tsx
  services/one-app/src/app/(site)/lost-found/_lib/comments.ts
  services/one-app/src/app/(site)/lost-found/_lib/get.ts
  services/one-app/src/app/(site)/lost-found/page.tsx
  services/one-app/src/app/globals.css
  services/one-app/src/common/assets/graphics/character/no-results.svg
  services/one-app/src/common/assets/icons/mic.svg
  services/one-app/src/common/assets/icons/svgs/chevron.svg
  services/one-app/src/common/assets/lottie/loading.json
  services/one-app/src/common/components/Article/ArticleCard.tsx
  services/one-app/src/common/components/Article/ArticleDetail.suspense.tsx
  services/one-app/src/common/components/Article/ArticleImages.tsx
  services/one-app/src/common/components/Article/ArticleList.suspense.tsx
  services/one-app/src/common/components/Article/EmptyArticleList.tsx
  services/one-app/src/common/components/Article/RecommendArticleCard.tsx
  services/one-app/src/common/components/BaseSkeleton.tsx
  services/one-app/src/common/components/Comment/BaseCommentList.suspense.tsx
  services/one-app/src/common/components/Comment/BaseCommentList.tsx
  services/one-app/src/common/components/Comment/CommentCard.tsx
  services/one-app/src/common/components/Comment/EmptyCommentList.tsx
  services/one-app/src/common/components/Filter/DropdownFilter.tsx
  services/one-app/src/common/components/Filter/ResetFilter.tsx
  services/one-app/src/common/components/Spinner.tsx
  services/one-app/src/common/constants/fallback-action.ts
  services/one-app/src/common/hooks/useIsDeferred.ts
  services/one-app/src/common/hooks/useIsomorphicLayoutEffect.ts
  services/one-app/src/common/hooks/useTimemout.ts
  services/one-app/src/common/utils/date.ts
  services/one-app/src/common/utils/number.ts
  services/one-app/src/common/utils/validate.ts
  services/one-app/src/model/Comment.ts
  services/one-app/src/model/Post.ts
  services/one-app/src/styles/global.css
  services/one-app/tailwind.config.ts
  yarn.lock
Labels: ✨ Feat
