Repository ahachulTeam/ahachul_web, pull requests merged in 2024-10, with the labels that each got.

#219 feat: add github pr template and codeowners file
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: 📃 Documentation

#218 feat: ahhachul.com - management filters and sync with api call
  .pnp.cjs
  services/ahhachul.com/src/features/subway-lines/data/index.ts
  services/ahhachul.com/src/features/subway-lines/model/index.ts
  services/ahhachul.com/src/pages/communicate/api/get-comments.ts
  services/ahhachul.com/src/pages/communicate/api/get-detail.ts
  services/ahhachul.com/src/pages/communicate/api/get-list.ts
  services/ahhachul.com/src/pages/communicate/data/index.ts
  services/ahhachul.com/src/pages/communicate/model/index.ts
  services/ahhachul.com/src/pages/communicate/slice/index.ts
  services/ahhachul.com/src/pages/communicate/ui/Page/Page.css.ts
  services/ahhachul.com/src/pages/communicate/ui/Page/Page.tsx
  services/ahhachul.com/src/pages/communicate/ui/_common/CommunityArticleList/CommunityArticleList.tsx
  services/ahhachul.com/src/pages/communicate/ui/_common/CommunityFilters/CommunityFilters.tsx
  services/ahhachul.com/src/pages/complaint/api/get-detail.ts
  services/ahhachul.com/src/pages/complaint/api/get-list.ts
  services/ahhachul.com/src/pages/lost-found/api/get-detail.ts
  services/ahhachul.com/src/pages/lost-found/api/get-list.ts
  services/ahhachul.com/src/pages/lost-found/data/index.ts
  services/ahhachul.com/src/pages/lost-found/model/index.ts
  services/ahhachul.com/src/pages/lost-found/slice/index.ts
  services/ahhachul.com/src/pages/lost-found/ui/Page/Page.tsx
  services/ahhachul.com/src/pages/lost-found/ui/_common/LostFoundArticleList/LostFoundArticleList.tsx
  services/ahhachul.com/src/pages/lost-found/ui/_common/LostFoundFilters/LostFoundFilters.tsx
  services/ahhachul.com/src/shared/lib/config/timestamp/index.ts
  services/ahhachul.com/src/shared/lib/hooks/useQueryParams.ts
  services/ahhachul.com/src/widgets/filters/data/uniqueId.ts
  services/ahhachul.com/src/widgets/filters/lib/useKeywordSearch.ts
  services/ahhachul.com/src/widgets/filters/model/index.ts
  services/ahhachul.com/src/widgets/filters/slice/filters.ts
  services/ahhachul.com/src/widgets/filters/ui/DrawerFilter.tsx
  services/ahhachul.com/src/widgets/filters/ui/DropdownFilter.tsx
  services/ahhachul.com/src/widgets/filters/ui/Filter.css.ts
  services/ahhachul.com/src/widgets/filters/ui/FilterContext.tsx
  services/ahhachul.com/src/widgets/filters/ui/FilterGroup.tsx
  services/ahhachul.com/src/widgets/filters/ui/FilterManager.tsx
  services/ahhachul.com/src/widgets/filters/ui/SearchFilter.tsx
  services/ahhachul.com/src/widgets/layout/ui/ComposeLayout.tsx
  services/ahhachul.com/src/widgets/layout/ui/Layout.css.ts
Labels: ✨ Feat

#230 feat: One App 환경 세팅
  .pnp.cjs
  .vscode/settings.json
  package.json
  services/one-app/.eslintrc.json
  services/one-app/.gitignore
  services/one-app/README.md
  services/one-app/jest.config.mjs
  services/one-app/jest.setup.js
  services/one-app/next.config.mjs
  services/one-app/package.json
  services/one-app/postcss.config.js
  services/one-app/public/next.svg
  services/one-app/public/vercel.svg
  services/one-app/src/app/(site)/layout.tsx
  services/one-app/src/app/(site)/login/_component/LoginButton.tsx
  services/one-app/src/app/(site)/login/loading.tsx
  services/one-app/src/app/(site)/login/page.tsx
  services/one-app/src/app/(site)/not-found.tsx
  services/one-app/src/app/(site)/page.test.tsx
  services/one-app/src/app/(site)/page.tsx
  services/one-app/src/app/_components/MSWComponent.tsx
  services/one-app/src/app/favicon.ico
  services/one-app/src/app/globals.css
  services/one-app/src/common/assets/fonts/pretendard/index.ts
  services/one-app/src/common/assets/fonts/pretendard/pretendard-variable.woff2
  services/one-app/src/common/assets/icons/PlusIcon.tsx
  services/one-app/src/common/components/ConditionalRender.test.tsx
  services/one-app/src/common/components/ConditionalRender.tsx
  services/one-app/src/common/utils/cn.ts
  services/one-app/src/common/utils/utils.ts
  services/one-app/src/middleware.ts
  services/one-app/src/model/Post.ts
  services/one-app/src/model/PostImage.ts
  services/one-app/src/model/User.ts
  services/one-app/src/store/count.ts
  services/one-app/tailwind.config.ts
  services/one-app/tsconfig.json
  yarn.lock
Labels: ✨ Feat

#233 refactor!: ci.yml, codeowners 수정
  .github/CODEOWNERS
  .github/workflows/ci.yml
  package.json
Labels: 🪛 Refactor
