Repository ahachulTeam/ahachul_web, pull requests merged in 2025-01, with the labels that each got.

#283 fix: import 관련 버그 수정
  services/one-app/next.config.mjs
  services/one-app/src/app/(site)/lost-found/_components/postDetail/PostDetail.tsx
Labels: ✨ Feat

#261 feat: 유실물 글 작성 페이지 구성
  services/one-app/components.json
  services/one-app/custom.d.ts
  services/one-app/package.json
  services/one-app/public/Group 5.svg
  services/one-app/public/mockServiceWorker.js
  services/one-app/src/app/(site)/lost-found/[lostId]/edit/page.tsx
  services/one-app/src/app/(site)/lost-found/_components/LostFoundCreate.tsx
  services/one-app/src/app/(site)/lost-found/_components/LostFoundDetail.tsx
  services/one-app/src/app/(site)/lost-found/_components/LostFoundEdit.tsx
  services/one-app/src/app/(site)/lost-found/_components/LostFoundForm.tsx
  services/one-app/src/app/(site)/lost-found/_components/SelectLineDrawer.tsx
  services/one-app/src/app/(site)/lost-found/_hook/useFormAdapter.tsx
  services/one-app/src/app/(site)/lost-found/_hook/useFormImage.tsx
  services/one-app/src/app/(site)/lost-found/_hook/useFormInitialize.tsx
  services/one-app/src/app/(site)/lost-found/_lib/post.ts
  services/one-app/src/app/(site)/lost-found/create/page.tsx
  services/one-app/src/app/(site)/page.tsx
  services/one-app/src/app/globals.css
  services/one-app/src/common/assets/icons/arrow-down.tsx
  services/one-app/src/common/assets/icons/arrow-left.tsx
  services/one-app/src/common/assets/icons/close-circle.tsx
  services/one-app/src/common/assets/icons/image-placeholder.tsx
  services/one-app/src/common/assets/icons/line/Incheon-one.svg
  services/one-app/src/common/assets/icons/line/Incheon-two.svg
  services/one-app/src/common/assets/icons/line/airport.svg
  services/one-app/src/common/assets/icons/line/eight.svg
  services/one-app/src/common/assets/icons/line/everline.svg
  services/one-app/src/common/assets/icons/line/five.svg
  services/one-app/src/common/assets/icons/line/four.svg
  services/one-app/src/common/assets/icons/line/gimpo-gold.svg
  services/one-app/src/common/assets/icons/line/gyeongchun.svg
  services/one-app/src/common/assets/icons/line/gyeonggang.svg
  services/one-app/src/common/assets/icons/line/gyeongui-jungang.svg
  services/one-app/src/common/assets/icons/line/nine.svg
  services/one-app/src/common/assets/icons/line/one.svg
  services/one-app/src/common/assets/icons/line/seohae.svg
  services/one-app/src/common/assets/icons/line/seven.svg
  services/one-app/src/common/assets/icons/line/shinbundang.svg
  services/one-app/src/common/assets/icons/line/sillim.svg
  services/one-app/src/common/assets/icons/line/six.svg
  services/one-app/src/common/assets/icons/line/suin-bundang.svg
  services/one-app/src/common/assets/icons/line/three.svg
  services/one-app/src/common/assets/icons/line/two.svg
  services/one-app/src/common/assets/icons/line/ui-sinseol.svg
  services/one-app/src/common/assets/icons/line/uijeongbu.svg
  services/one-app/src/common/assets/icons/mic.svg
  services/one-app/src/common/components/Carousel.tsx
  services/one-app/src/common/components/Drawer.tsx
  services/one-app/src/common/constants/subwayLines.ts
  services/one-app/src/lib/createFormData.ts
  services/one-app/src/model/LostFound.ts
  services/one-app/tailwind.config.ts
  yarn.lock
Labels: ✨ Feat

#294 chore: D-n 규칙에 따라 자동으로 Label 을 업데이트하는 Github Actions (#293)
  .github/workflows/d-day-labeler.yml
Labels: ⚙️ Chore, D-3

#298 feat: 토큰 재발급 (#296)
  services/ahhachul.com/src/apis/fetcher.ts
  services/ahhachul.com/src/apis/request/token.ts
  services/ahhachul.com/src/apis/request/user.ts
  services/ahhachul.com/src/components/domain/home/panel/index.ts
  services/ahhachul.com/src/components/domain/home/panel/testing/Stations.component.tsx
  services/ahhachul.com/src/pages/home/page.tsx
  services/ahhachul.com/src/services/user.ts
  services/ahhachul.com/src/utils/tokenService.ts
Labels: ✨ Feat, D-3

#299 feat: 커뮤니티 페이지 글 목록 조회
  services/ahhachul.com/src/apis/request/community.ts
  services/ahhachul.com/src/apis/request/index.ts
  services/ahhachul.com/src/apis/request/lostFound.ts
  services/ahhachul.com/src/components/common/filter/drawerFilter/DrawerFilter.component.tsx
  services/ahhachul.com/src/components/common/filter/drawerFilter/DrawerFilter.styled.tsx
  services/ahhachul.com/src/components/domain/community/index.ts
  services/ahhachul.com/src/components/domain/community/searchResults/filters/CommunityFilters.component.tsx
  services/ahhachul.com/src/components/domain/community/searchResults/filters/CommunityFilters.styled.tsx
  services/ahhachul.com/src/components/domain/community/searchResults/index.ts
  services/ahhachul.com/src/components/domain/community/searchResults/searchedList/SearchedList.component.tsx
  services/ahhachul.com/src/components/domain/community/searchResults/searchedList/SearchedList.styled.tsx
  services/ahhachul.com/src/components/domain/community/searchResults/skeleton/SearchedList.skeleton.styled.tsx
  services/ahhachul.com/src/components/domain/community/searchResults/skeleton/SearchedList.skeleton.tsx
  services/ahhachul.com/src/components/domain/index.ts
  services/ahhachul.com/src/constants/community.ts
  services/ahhachul.com/src/constants/index.ts
  services/ahhachul.com/src/hooks/domain/community/index.ts
  services/ahhachul.com/src/hooks/domain/community/useCommunityFilterStore.ts
  services/ahhachul.com/src/pages/community/page.tsx
  services/ahhachul.com/src/pages/lostFound/page.tsx
  services/ahhachul.com/src/services/community.ts
  services/ahhachul.com/src/services/lostFound.ts
  services/ahhachul.com/src/types/common.ts
  services/ahhachul.com/src/types/community.ts
  services/ahhachul.com/src/types/index.ts
  services/ahhachul.com/src/types/lostFound.ts
Labels: ✨ Feat, D-3

#306 feat: Native Bridge 대응 (#305)
  services/ahhachul.com/src/App.tsx
  services/ahhachul.com/src/components/common/gnb/Gnb.component.tsx
  services/ahhachul.com/src/components/common/gnb/navItem/NavItem.hook.ts
  services/ahhachul.com/src/components/common/index.ts
  services/ahhachul.com/src/components/common/iosBottomPadding/IOSBottomPadding.component.tsx
  services/ahhachul.com/src/components/common/iosBottomPadding/IOSBottomPadding.styled.tsx
  services/ahhachul.com/src/components/common/iosBottomPadding/index.ts
  services/ahhachul.com/src/components/common/list/listItem/ListItem.styled.tsx
  services/ahhachul.com/src/components/common/loading/Spinner.component.tsx
  services/ahhachul.com/src/components/domain/community/postDetail/headerActions/CommunityHeaderActions.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/headerActions/LostFoundHeaderActions.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/lost112InfoTable/Lost112InfoTable.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/lost112InfoTable/Lost112InfoTable.styled.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/recommendPostList/RecommendPostList.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/recommendPostList/listItem/ListItem.styled.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/template/LostFoundDetail.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/template/LostFoundDetail.styled.tsx
  services/ahhachul.com/src/components/layout/BaseLayout.component.tsx
  services/ahhachul.com/src/constants/appEnv.ts
  services/ahhachul.com/src/constants/index.ts
  services/ahhachul.com/src/constants/path.ts
  services/ahhachul.com/src/contexts/index.ts
  services/ahhachul.com/src/contexts/native-bridge.tsx
  services/ahhachul.com/src/hooks/index.tsx
  services/ahhachul.com/src/hooks/useBackAction.ts
  services/ahhachul.com/src/hooks/useTimeout.ts
  services/ahhachul.com/src/types/custom.d.ts
  services/ahhachul.com/src/types/index.ts
  services/ahhachul.com/src/types/nativeBridge.ts
  services/ahhachul.com/src/types/share.ts
  services/ahhachul.com/src/types/window.d.ts
  services/ahhachul.com/src/utils/common.ts
  services/ahhachul.com/src/utils/format.ts
  services/ahhachul.com/src/utils/share.ts
  services/ahhachul.com/src/vite-env.d.ts
Labels: ✨ Feat, D-3

#307 chore: develop to main
  services/ahhachul.com/src/App.tsx
  services/ahhachul.com/src/components/common/gnb/Gnb.component.tsx
  services/ahhachul.com/src/components/common/gnb/navItem/NavItem.hook.ts
  services/ahhachul.com/src/components/common/index.ts
  services/ahhachul.com/src/components/common/iosBottomPadding/IOSBottomPadding.component.tsx
  services/ahhachul.com/src/components/common/iosBottomPadding/IOSBottomPadding.styled.tsx
  services/ahhachul.com/src/components/common/iosBottomPadding/index.ts
  services/ahhachul.com/src/components/common/list/listItem/ListItem.styled.tsx
  services/ahhachul.com/src/components/common/loading/Spinner.component.tsx
  services/ahhachul.com/src/components/domain/community/postDetail/headerActions/CommunityHeaderActions.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/headerActions/LostFoundHeaderActions.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/lost112InfoTable/Lost112InfoTable.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/lost112InfoTable/Lost112InfoTable.styled.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/recommendPostList/RecommendPostList.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/recommendPostList/listItem/ListItem.styled.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/template/LostFoundDetail.component.tsx
  services/ahhachul.com/src/components/domain/lostFound/postDetail/template/LostFoundDetail.styled.tsx
  services/ahhachul.com/src/components/layout/BaseLayout.component.tsx
  services/ahhachul.com/src/constants/appEnv.ts
  services/ahhachul.com/src/constants/index.ts
  services/ahhachul.com/src/constants/path.ts
  services/ahhachul.com/src/contexts/index.ts
  services/ahhachul.com/src/contexts/native-bridge.tsx
  services/ahhachul.com/src/hooks/index.tsx
  services/ahhachul.com/src/hooks/useBackAction.ts
  services/ahhachul.com/src/hooks/useTimeout.ts
  services/ahhachul.com/src/types/custom.d.ts
  services/ahhachul.com/src/types/index.ts
  services/ahhachul.com/src/types/nativeBridge.ts
  services/ahhachul.com/src/types/share.ts
  services/ahhachul.com/src/types/window.d.ts
  services/ahhachul.com/src/utils/common.ts
  services/ahhachul.com/src/utils/format.ts
  services/ahhachul.com/src/utils/share.ts
  services/ahhachul.com/src/vite-env.d.ts
Labels: ⚙️ Chore
